### ISSUE TITLE
Open Graph Banner Images for Mirlo

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#100]
Can be tested here https://www.opengraph.xyz/url/https%3A%2F%2Fmirlo.space%2F

**Comment by simonv3** [comment]
So I think this won't work with that URL specifically because netlify doesn't recognize those URLs as a user agent https://answers.netlify.com/t/support-guide-understanding-and-debugging-prerendering/150#which-requests-are-prerendered-1

**Comment by bentooth** [comment]
hmm. would we be open to hosting the client on the server? we could then inject the metadata based on the URL into the index.html being served? probably complicates things tho :/

**Comment by simonv3** [comment]
Yeah, I'm not opposed and we'd need to do that as part of getting to self-install process (and also custom [subdomains for artists](https://github.com/funmusicplace/mirlo/issues/17)). Switched to netlify for the reason of using prerendering #66
