### ISSUE TITLE
Why does the android 512 icon sometimes get added to the bottom of a page? 

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#106]
It's used only in a meta tag. 

Also we should detect if the player is up or not and automatically add that height to the margin of the main container.

Edit: I removed some of the header stuff to try and test some helmet display open graph display things (which don't seem to have worked) and now it's loading `src="/apple-touch-icon.png"` which seems to imply it has something to do with the react template?

**Comment by timglorioso** [comment]
Any screenshot of this? Does it depend on the device?

**Comment by simonv3** [comment]
I think I've seen it happen both on desktop and on mobile. It's basically every time there seems to be a large empty space at the bottom of the page. The image itself doesn't appear but it does block out space for itself. I'll take a screenshot of it next time.

**Comment by simonv3** [comment]
I haven't seen this in a while. closing.
