### ISSUE TITLE
Album Cover image size.

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#121]
1/ Image size should be slightly smaller if we stick with 600x600

We should try to avoid having the album cover being displayed above image size definition. Bandcamp recommends 1400x1400. I think we'd be ok with 1080x1080. Right now the image displayed is compressed down to 600x600. If we decide to keep that compression for pragmatic limitation purposes, then image size should be smaller than 600px to avoid the compression being too damaging visually.

2/ Image size should be a responsive percentage of viewport height as to always have some margin above and below and keep the balance of the page elegant. Currently, image can be cropped by the sticky-footer player bar. 

Ideally, the "main section" (to be defined what belongs in that section) before the "album description / about section" appears should be the full size of the viewport height minus the sticky footer player to avoid the kind of uneven proportion shown in the linked screencap (![2023-10-15_144050](https://github.com/funmusicplace/mirlo/assets/77789607/e9ded706-e302-4bc1-98b4-b7fc91e7ad74). If we want to make clear that there's more below we could have an arrow somewhere indicating that but I don't think it's really necessary as people are used to scrolling anyway.

**Comment by simonv3** [comment]
fwiw these are the artwork sizes 
![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/00b0ea46-593f-4eed-a949-9569df1cb1fb)

**Comment by LouisLouiseKay** [comment]
How does it pick the size? I feel like on a QHD full screen desktop computer it should be at max size but I never see it above 600x600.

**Comment by simonv3** [comment]
The front-end just does the 600px at the moment, we'd have to change that based on screen size.
