### ISSUE TITLE
Album URL

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#123]
"Tg" in URL Should be either "Album", "Release" or "EP/LP/Single"

**Comment by simonv3** [comment]
Hmm, having it be dynamic like that I feel like adds a lot of complexity. Which one of the three would you prefer?

**Comment by LouisLouiseKay** [comment]
Release seems to be the best candidate then, ubiquitous and works with any format.

**Comment by simonv3** [comment]
Also going to add to this ticket that we should cast the URL slug to lowercase before saving.
