### ISSUE TITLE
Home page isn't being translated

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#141]
We need to add the strings to en.json and then push it to transifex

**Comment by timglorioso** [comment]
Would love to learn the ropes on this one

**Comment by simonv3** [comment]
@timglorioso dope! 

So we use [transifex](https://app.transifex.com/) as our host for translations. It has some limitations because we're using the free tier but we're using that because it means translators don't have to edit json files (or we have to edit json files with passed on translations). 

Then in React we use https://github.com/i18next/react-i18next for handling translation, and in most cases that means using the translation hook `const { t } = useTranslation(...)` that gives us the `t` function, to which you pass a key like `t('signup.Login`)`. Locally those values are stored in `/client/src/translation/en.json` (and you're already familiar with loading those in `i18n.js`). 

So in this case we'll have to move the text from `Home.tsx` to `en.json` probably in a `home` object (so that it gets accessed as `home.mainText`. But for links I think we'll need to use the `<Trans>` component. 

Then once the `en.json` file is updated with the new strings we'll need to send it to transifex, for which there's a command I can just send you.

**Comment by simonv3** [comment]
Done by #178
