### ISSUE TITLE
Elements not on Transifex or broken with transifex translation

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#144]
List of things yet to be added to Transifex for translation :

- [x] Stripe account verified!
- [x] Mirlo is under construction. If you'd like to contribute check out [the code on GitHub](https://github.com/funmusicplace/mirlo/), [join our Discord](https://discord.gg/VjKq26raKX), or [email us](mailto:mirlodotspace@proton.me).
- [x] [About us](https://mirlo.space/about).
- [x] Changing your email has been disabled for now. Please contact an admin if you want to do so
- [x] There's nothing in your collection yet, support some artists and buy their music!
- [x] Downlaod Subscriber Data
- [x] Your subscription tiers
- [x] Create new artist (actually in transifex it says "create artist" so there's a discrepency here)
- [x] Titles / Published / Tracks / Release Date (On the album card in artist management)
- [x] Edit / Delete (in the subscription tier section)
- [x] Search artists

**Comment by simonv3** [comment]
There's two things that probably need to happen:

If the text is written as plain english in the code:

![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/932daa24-050c-40ae-9a88-794582a37c5c)
![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/3ff1c15e-2c92-4b88-b3e6-f04d4df72882)

Then that needs to be changed to use i18n-next react's useTranslation hook. 

![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/18e684e5-0876-4798-aae7-a70c6619f068)
![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/df4aa24d-af0a-4881-b004-565836a6610e)

And the relevant things need to be added to `en.json`. 

Once that's done someone with the transifex keys & codes for Mirlo can push the content of `en.json` to transifex (DM me). That will update the list of phrases in transifex (updating the related english phrase if necessary too).  

The actual content of the different languages (french, dutch, Arabic, etc) is managed _on_ the transifex website.  If you want to add a language, or further translate those phrases, you do it on the website. 

Once a language is translated fully, we can add it to the list of done languages in `i18n.ts` in the code. Currently that's just french and english.

**Comment by simonv3** [comment]
The option to add these were added in #178
