### ISSUE TITLE
Docs endpoint is broken

### ISSUE THREAD

**Issue by ismailghedamsi** [funmusicplace/mirlo#148]
When I go to http://localhost:3000/docs I get htis error

Parser error on line 13
end of the stream or a document separator is expected

![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/89232446-d40d-45c5-bd86-af3fd36f7911)

**Comment by simonv3** [comment]
Hmm, this seems to be fine on my local now that I'm able to try it out. And IIRC there were no obvious errors in the docker command. What system are you running on?

**Comment by ismailghedamsi** [comment]
Ubuntu 20.04

**Comment by ismailghedamsi** [comment]
It's working after replacing undefined with apiDoc as the first parameter of  swaggerUi.setup

**Comment by simonv3** [comment]
Oh interesting! Wonder why that works fine for me but not on your end. Wanna put in a Pull Request with that fix?
