### ISSUE TITLE
Impossible to delete albums

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#170]
There is currently no way to delete albums in the artist management page.

**Comment by simonv3** [comment]
So this kind of forces the question: what should happen for a user who bought your album?

**Comment by LouisLouiseKay** [comment]
Agreed, I think this is an important discussion. My opinion so far is bare minimum : People who "own" the album get a warning with a download link to go download their purchase. Then it's about how long we want to keep the album in our db for the people who bought it to still be able to download it (6 months? A year? Forever?).

Then another interesting question is : what if people decide to upload it again ? Should we keep some informations relative to it (for example : who purchased it) so that we can propose artists re-uploading it to link to that data? 

Complex issues but I think for the MVP / Simplest version : Delete needs to be possible. People who purchased need to be informed. When informed they need to be able to download for a period of time.

**Comment by simonv3** [comment]
Bandcamp does this: 

> Because there is a possibility that we may be required to deny you access to previously purchased Content, we encourage you to promptly download any Content you purchase through the Site to your own devices so that you will retain control and possession of such Content even if we are required to remove the Content from the Service.)

**Comment by simonv3** [comment]
FWIW I made it possible to delete unpublished unreleased albums.

**Comment by bentooth** [comment]
Maybe having the ability to "hide" a (published/released) album from the UI. users who have purchased the music will be continue to be able to stream and download but not be visible in the UI once hidden via some db flag
