### ISSUE TITLE
Bulk Upload Bug (Local Version) - "There Was A Problem With The API"

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#173]
When trying to upload tracks, it says "there was a problem with the API" in the notification pop up at the bottom right, and I have this error in the docker compose up output.
![2023-10-28_151148](https://github.com/funmusicplace/mirlo/assets/77789607/4a0abc19-d8e5-4da9-9eb6-7cf0e3da188c)
![2023-10-28_151243](https://github.com/funmusicplace/mirlo/assets/77789607/f9dda890-5388-472c-836c-c7fb74f403c7)

**Comment by simonv3** [comment]
Can you do `docker-compose down` and `docker-compose up` again?
