### ISSUE TITLE
Album Manage page doesn't appear

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#174]
The Album Manage button sends to a blank page
![2023-10-28_152049](https://github.com/funmusicplace/mirlo/assets/77789607/5fc8164f-86d7-4401-920d-425f97537430)

**Comment by simonv3** [comment]
this seems to happen with albums with 0 tracks on them.

**Comment by LouisLouiseKay** [comment]
Yeah which is all albums when you first create them ahah (which is a step that should be removed anyway you should be able to add tracks right away)

**Comment by simonv3** [comment]
This was happening cause we were fetching from the public api instead of the user specific api (which meant that an unpublished album wasn't being retrieved)
