### ISSUE TITLE
Add "bulletpoint" fields in subscription tier description

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#230]
Not a personnal preference, but I've noticed it's common place to have "bulletpoints" of perks that go with subscription tiers. Maybe we could add that to the "edit subscription tier" form.

**Comment by simonv3** [comment]
Is this satisfied with making sure the subscriptionTier.description prints out as markdown? 

![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/51d1d10a-04ff-457f-8969-c72d3b74719c)

**Comment by simonv3** [comment]
Fixed in latest merge
