### ISSUE TITLE
Create a way to have access to "excerpt" and "date creation" for blogposts

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#231]
These are two things needed to not have to display full blogposts on the artist page.

* [x] publishedAt
* [ ] excerpt

**Comment by simonv3** [comment]
`post.publishedAt` is the "date creation" you're looking for right? That exists. `post.createdAt` is the date it's literally created, but it could be a draft.

**Comment by LouisLouiseKay** [comment]
If that's a simpler course of action than having a way to do word count to have an "xxx words excerpt" of the post, we should go with adding a field for people to add a post description (or just an excerpt of their choosing). It's just to have a small bit of text that people can click on to read more.
