### ISSUE TITLE
Download Codes

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#236]
Ok just putting it out there so we have a ticket to track progress on that. Very simple, we'd need download codes.

Unlike Bandcamp we shouldn't lock that behind a scaled limit (groups of 100, and need to pay after a certain amount), at least unless we see a problem with that.

**Comment by simonv3** [comment]
Just clarifying this is distinct from the feature where upload Bandcamp's download codes right? Or could they basically be the same? (ie, either generate our own codes or upload Bandcamp's?)

**Comment by LouisLouiseKay** [comment]
So yes it's separate in that we're the ones creating the codes.

The one thing I hadn't thought of though, is how Bandcamp codes could be compatible with Mirlo? That's an interesting thought.

But yeah for another ticket the feature I had in mind for BC codes is slightly different because they'd be offered to people who purchase on Mirlo, those don't need a code on Mirlo since they've already bought music there. It's just the artist offering them a way to add their purchase to their Bandcamp collection as well. (I'll write a ticket for it) 

In this case, it's about create codes so people who HAVEN'T bought can download the album and add it to their collection (for Press, for people who purchased physical merch at shows so they can redeem a download, etc.)

**Comment by simonv3** [comment]
Here's what I imagine needs to happen:

We'll need a table for `TrackGroupDownloadCodes`:

| trackGroupId | downloadCode | group |
| --- | --- | --- |

Then when a download code gets entered, the owner of the code has to either be logged in or enter their e-mail address, and we create a `TrackGroupPurchase` value for that user (and create a user if that e-mail address isn't tied to an account).
