### ISSUE TITLE
Mirlo keeps disconnecting in production

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#311]
On mobile (couldn't test on desktop) I keep being disconnected from Mirlo. When trying to reconnect I get these two different errors depending on wether I try in Firefox or Chrome.

Firefox error
![Screenshot_2023-11-26-19-15-14-757_org mozilla firefox](https://github.com/funmusicplace/mirlo/assets/77789607/bd440fbd-5b46-4d96-9c53-a5786e61f2b3)

Chrome error
![Screenshot_2023-11-26-19-15-33-751_com android chrome](https://github.com/funmusicplace/mirlo/assets/77789607/bd40dec9-2d91-488b-aadf-ca31a678e459)

**Comment by LouisLouiseKay** [comment]
I was just browsing the site, and I noticed I got disconnected when I tried to go to my collection.

**Comment by simonv3** [comment]
Fixed I think with bumping rate limiting
