### ISSUE TITLE
Unfollow doesn't seem to work 

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#316]
When clicking unfollow it doesn't goes back to "follow" instead "unfollow" stays active and when you come back to the page you're still following.

**Comment by LouisLouiseKay** [comment]
Ok so the bug is : 

If you don't follow anyone. But then starts following any account, the follow button then indicates "unfollow" on every other artist page as if you'd followed them. However since you're not actually following them, clicking the unfollow button doesn't acheive anything.

Returning to the original artist you followed and unfollowing turns everything back to normal.

**Comment by simonv3** [comment]
Should be fixed

**Comment by LouisLouiseKay** [comment]
It's still somehow happening for me :-/
