### ISSUE TITLE
Albums are not ordered ny release date

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#320]
It seems album are not ordered by release date. Even weirder, their order is different on Releases page and on artist page, none of which are in chronological release date order.

MOWUKIS artist page goes (from top left to bottom right) 2020 > 2016 > 2017 > 2023

The same releases on Releases page are in the order (from top left to bottom right) 2017 > 2016 > 2020 > 2023

**Comment by LouisLouiseKay** [comment]
It's fixed on release page but not on artist page!

**Comment by simonv3** [comment]
@LouisLouiseKay is this fixed now? I'm not sure what your album release order is :P

**Comment by LouisLouiseKay** [comment]
Fixed!
