### ISSUE TITLE
Add notification feed in the App

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#321]
Basically a timeline/feed of all the notifications sent by mail to users : "x followed you" "y bought x album" "z subscribed at n tier"

**Comment by simonv3** [comment]
So I think we'll need a new table for this that we insert notifications into. I'm not sure what a great design for that looks like, but it's probably similar to what we're sending to e-mail (and maybe uses the same templates?)

I feel like an easy way to do this is to just add a function call in `sendMail` that inserts a notification into a table, with the html as the content of the notification? 

So then the proposed table becomes:

| id | title | contentHtml | toUserId | 
|---|---|---|---|

**Comment by simonv3** [comment]
Remaining tasks:

* [ ] Show notification feed, probably in the top right corner
* [ ] Mark notifications as read when hovered over in the notification feed
* [ ] Limit notification feed to show 10 most recent notifications (we can expand to do more)
