### ISSUE TITLE
Loading spinners turning when there's no about / credit section in album page 

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#352]
If an album page has no credit section or about informations you get this ![Screenshot_2023-12-07-10-27-59-356_com.android.chrome-edit.jpg](https://github.com/funmusicplace/mirlo/assets/77789607/04409631-56c3-49cb-b8d3-63e0a6085a5c)

**Comment by simonv3** [comment]
Fixed I think
