### ISSUE TITLE
When uploading tracks without ID3Tag (wav) they're upload from last to first

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#401]
If you do batch upload of a lot of tracks without a tag, instead of proposing the order from first to last (before upload), it proposes to upload from last to first, forcing the user to change the number of every track manually. 
![2023-12-22_150744](https://github.com/funmusicplace/mirlo/assets/77789607/2249a7bb-268b-4d0c-bdc5-457756b5a653)

**Comment by simonv3** [comment]
Is this still happening @LouisLouiseKay
