### ISSUE TITLE
Bug: Subscription tiers show price in USD even if artist profile is set to a different currency

### ISSUE THREAD

**Issue by samnabi** [funmusicplace/mirlo#429]
I have selected CAD as my currency for Stripe, but the subscription tiers are showing up in USD.

**Comment by axwax** [comment]
Hi, I think I'm encountering the same bug:

When I clicked Buy on an album that had its currency set to NOK the text field underneath says "Name your price in USD:" with the price in NOK as default.

![ecc2e4b7b687f7f2](https://github.com/funmusicplace/mirlo/assets/590109/1ae64067-e755-46b7-9176-47da262c42e6)

**Comment by simonv3** [comment]
@axwax should be fixed, let me know if you encounter it again
