### ISSUE TITLE
Allow editing artist permalink

### ISSUE THREAD

**Issue by samnabi** [funmusicplace/mirlo#430]
Once created, the artist's slug can't be changed. I think we should allow this to be edited.

I created an Artist "Sam Nabi" which auto-populated a slug "sam-nabi". In the artist creation form, I edited this to remove the hyphen, but after proceeding to the next screen I found that the original "sam-nabi" slug was still there.

Since I couldn't edit the slug I deleted the artist and tried to create a new one. Now, I couldn't pick the name "Sam Nabi" again because it said the permalink "sam-nabi" was already taken (`Value is not unique: URL Slug`). Since I didn't want the hyphen to begin with, I made the same of this new artist "SamNabi". Then, once it was created, I edited the artist name back to "Sam Nabi".

I think there may be two issues here:

1. Bug: Changes to artist permalink don't save properly upon creating a new artist
2. Feature request: Permalink can't be edited after the fact

**Comment by simonv3** [comment]
This shouldn't be too difficult but we wanna make sure that we're checking the uniqueness of the urlSlug before submitting it.
