### ISSUE TITLE
Bug: text from my release description ended up in another artists' release

### ISSUE THREAD

**Issue by novakeith** [funmusicplace/mirlo#447]
Here is my release: https://mirlo.space/knova/release/collected-oddities-(2012-2019)

Here is a release I was randomly browsing: https://mirlo.space/mowukis/release/o

Not sure why, but the release by mowukis ended up with some of the text from my release in the 'description' field. Not sure if this was a weird copy/paste error at some point if mowukis was updating their own release. I have not noticed it on any other albums I've browsed.

**Comment by simonv3** [comment]
That's very weird. I can't really imagine what would cause that, considering it's kept the same text at the start of the post. When we send the text to the API we just replace everything entirely. @LouisLouiseKay ?

**Comment by LouisLouiseKay** [comment]
Sorry this is completely on me I've been copy pasting your text for debugging to see what caused overflow 🫣

**Comment by simonv3** [comment]
Solution: LLK gets his local environment working again

**Comment by novakeith** [comment]
lol - thanks all
