### ISSUE TITLE
Update Sharp NPM package

### ISSUE THREAD

**Issue by Chickensoupwithrice** [funmusicplace/mirlo#471]
@simonv3 asked if I'd be interested in updating the Sharp package. 

they mentioned It'll also mean updating the node version of the docker containers in Dockerfile to a more recent one, and likely also updating the minio package version as an effect of that

Creating this issue to track that

**Comment by Chickensoupwithrice** [comment]
I can't assign myself to issues, otherwise I would've

**Comment by simonv3** [comment]
> it's been giving me more trouble than i anticipated. the NODE_VERSION on newer alpine docker images seems to clash with sharp's expectations
