### ISSUE TITLE
Description text in MetaCard should include artist name

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#478]
Right now it says `An album on Mirlo` but it should probably say `An album by <artist> on Mirlo`

**Comment by rdhss** [comment]
hello @simonv3 can i work for this task?

**Comment by simonv3** [comment]
@rdhss Yes please! Assigned it to you :)

**Comment by rdhss** [comment]
hi @simonv3 is there demo account to get into development site? i've been trying to figuring out to login but having issue with that. i cant register from development cause error will pop that say ```This client does not exist``` and i cant use account from main website to login to development site

and may i know where metacard that contain text ```An album on Mirlo```

**Comment by simonv3** [comment]
Hey @rdhss it sounds like you have to run the seeding script. That's detailed in the readme, but this should set you up: 

```
docker exec -it blackbird-api npx prisma db seed
```

The `MetaCard` component is inserted in `src/client/components/TrackGroup.tsx`

**Comment by rdhss** [comment]
i already set up seed, the sign up is success and also on log said the email just send to my email but i when check my email the confirm email never show up and also on the spam 
this is my email that i used to sign up : 
whateverman1221@gmail.com
fadildu71@gmail.com
fadilwu6@gmail.com

**Comment by simonv3** [comment]
@rdhss If this is local then they'll appear in the docker logs.
