### ISSUE TITLE
Clicking on an artist page breaks backwards button

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#501]
If you click on an artist page, you can't use the "backward" history button in the browser. I think this only happens since we've added the tabs, because when you click instead of linking you to the urlslug of the artists it then moves you over to either "releases" or "support" and that's probably where the history breaks and can't track down where it came from. 

This is especially frustrating when you're not logged in because since you don't have any other way to come back to the Mirlo home page, you need to manually re-enter the adress in the topbar. (Maybe we could find a way to link to mirlo homepage through the login icon like, the modal could be "Login" and underneath a "Go to Mirlo.space" link )

**Comment by simonv3** [comment]
Yeah this is happening because we `navigate` to a default page dependent on what the artist has set up (if they don't have albums, we go to posts, if they don't have posts we go to support). I'll think about how this is done to make that better.
