### ISSUE TITLE
Switch off of create-react-app and to something like vite

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#52]
CRA is no longer maintained. We should update to something like vite. 

https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741

**Comment by timglorioso** [comment]
Throwing [Parcel](https://parceljs.org) into the mix.

Noting that Vite currently requires a [separate third-party package](https://github.com/marcofugaro/browserslist-to-esbuild) to use `browserslist`, as well as a [plugin](https://github.com/vitejs/vite/tree/main/packages/plugin-legacy) for any older browsers that don't support ES2015. caniuse data suggests that the global usage difference between browsers supporting ES5 and ES2015 (ES6) is about 1%.

Vite would probably be a good choice, but wanted to call out browser compatibility in the ethos of Mirlo :)

**Comment by simonv3** [comment]
@timglorioso that works for me! I haven't used either before.
