### ISSUE TITLE
Image uploaded as not square

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#520]
![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/981dc753-1114-49d7-9865-d5cf3e643b73)

How do we prevent users from doing this? Do we need to? Not sure @LouisLouiseKay thoughts?

**Comment by LouisLouiseKay** [comment]
Ah yeah, actually, it crops well to a square when the height is more than the width, so I'll have to give it some thoughts but it should be manageable, I'll have to work on that locally. 

The image uploader tool could probably crop on the way in the way it does it for the background, but I liked the idea of being able to have non-square images on the album page though, which would mean we only crop the thumbnails in the "releases / albums" sections.

**Comment by samnabi** [comment]
<img width="1223" alt="Screen Shot 2024-03-16 at 12 30 26 PM" src="https://github.com/funmusicplace/mirlo/assets/1731536/982d338a-957a-4e11-b367-2e3dd15044f8">

Another example of a non-square album cover, for illustration. I do think it should be cropped to square for the releases/albums sections.
