### ISSUE TITLE
Allow for PNG image uploads with transparency

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#528]
This could allow for more playful uses of the artist page (especially if we had Banners later on where artists could display informations on top of the Background) most notably Avatar where artists wouldn't be as bound by the round box than they currently are.

**Comment by simonv3** [comment]
Okay this is happening because images are being converted to webp and jpg, but not png. So I added png conversion to this, but I feel like we should also keep track of what it as uploaded as originally (or just show png?)

**Comment by LouisLouiseKay** [comment]
I think Webp can handle transparency? Not sure. If possible maybe we could keep original file + webp for optimization purposes on page load.

**Comment by simonv3** [comment]
Wonder if this is fixed with #772
