### ISSUE TITLE
BUG - Unable to edit an artist using a created user account

### ISSUE THREAD

**Issue by RockManJoe64** [funmusicplace/mirlo#568]
## Steps to Reproduce

Given I am logged into Mirlo using a created account, 
When I edit a selected artist's details, 
Then Mirlo should allow me to successfully save the changes.

1. Create a non-admin account in Mirlo
2. Log into the created account
3. Create an artist while filling out the URL field
4. Save the artist
5. Go to Manage Artists
6. Select an artist to edit
7. Click on Edit Artist Details
8. Make a modification to any field other than the URL field
9. Click on Save Artist

## Expected Result

The Edit Artist Details page should save the changes.

## Actual Result

The "Text That Will Appear in the URL" field is highlighted and the validation error "This needs to be unique, try something else" is displayed.

![image](https://github.com/funmusicplace/mirlo/assets/1872995/89ed3baf-c93a-456b-9f21-e0c5cb28e4fb)

## Open Questions

According to the team, created users should be allowed to create and manage artists on the platform. This may be related to the idea of an admin being able to modify the URL. 

- Should this bug be fixed to allow created users to still edit an artist detail by disabling the ability to edit the URL?
- Should created accounts be allowed to modify the URL? 
- Should URLs, once created, be immutable? If the URL is changed, that would break existing bookmarks and other references to the artist URL.

**Comment by simonv3** [comment]
Deploying a fix now, should be available in 10 minutes. Let me know if that lets you create a user!

**Comment by LouisLouiseKay** [comment]
It seems fixed for me after testing today.
