### ISSUE TITLE
Add tags or genres

### ISSUE THREAD

**Issue by ismailghedamsi** [funmusicplace/mirlo#598]
Any plan on adding them.

**Comment by simonv3** [comment]
Hey @ismailghedamsi we have tags that include both genres and other ways of tagging music, for example `rock`: 

https://mirlo.space/releases?tag=rock

(though I do notice there's a bug with the header displaying `<strong>`)

And you can see them on albums too 

https://mirlo.space/avalanches/release/megalithe

![afbeelding](https://github.com/funmusicplace/mirlo/assets/485583/0b526d0a-ec8b-4ed3-99b8-2194c29e3ae8)

Additionally, please check out the existing discussion around tags https://github.com/funmusicplace/mirlo/discussions/166
