### ISSUE TITLE
Json error on new account

### ISSUE THREAD

**Issue by PaulHendriks** [funmusicplace/mirlo#607]
At my first attempt to register, the sign up form gave a failed to parse Json error. After trying to login, and returning to the register page again (my details where still filled in) tried to submit again and this time it succeeded 😃 I've received an email, will complete the registration.

Just wanted to let you know that the registration flow acted a bit strange.

I'm on Android 11, using Firefox.
Url with sign up form https://mirlo.space/signup

![Screenshot_20240303-193447](https://github.com/funmusicplace/mirlo/assets/17846767/ce41693f-716d-4b12-95f3-9f1485e5fda6)

**Comment by simonv3** [comment]
Certainly weird, I'll try to reproduce!

**Comment by PaulHendriks** [comment]
I can't reproduce it on a desktop. It registered on the first try with the same settings as i used before.

**Comment by simonv3** [comment]
Found an error in the server logs:

```
fo{
info  data: {
info    name: undefined,
info    email: "<redacted>",
info    receiveMailingList: "<AN EMAIL ADRESS!!>",
info                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
info    password: "redacted"
info  },
info  select: {
info    name: true,
info    email: true,
info    id: true,
info    receiveMailingList: "<redacted>",
info    emailConfirmationToken: true
info  }
info}
info
infoArgument `receiveMailingList`: Invalid value provided. Expected Boolean, provided String.
```

That means the form sent back a string (the same value as what was in the email field) for the `receiveMailingList` input which is an html input. I wonder if there's some browser behavior that auto-filled the checkbox a bit aggressively?

Either way, I cast the value to a boolean now and that should fix it once it's deployed.
