### ISSUE TITLE
Links with '@' are treated as emails even when not emails

### ISSUE THREAD

**Issue by instruments-of-the-aviary** [funmusicplace/mirlo#668]
I added my youtube channel using the my [youtube handle](https://support.google.com/youtube/answer/11585688). My link is `https://www.youtube.com/@wrenharmonic`. When hitting Save Links it detects the '@' character and decides this is an email link, so it prepends `mailto:` to the link.

Determining what's an email by text alone (e.g. using regex) is a famously hard problem so I'm not sure what the right solution is.

One option is to add a couple more layers of detection here. Maybe capturing the `https://` (or `http://`) would be enough to let users force a link to not read as email for now.
Another option is to add a UI option to force a link to be a special type, or at least a way to prevent a link from rendering as a special type if detected.

**Comment by jayrope** [comment]
+1

**Comment by keefmarshall** [comment]
This affects Mastodon (and probably other Fediverse) links as well, so +1 from me. 

Maybe checking for an already formatted URI with a protocol before looking for the '@' would eliminate this.
