### ISSUE TITLE
Listed Artists field not saving

### ISSUE THREAD

**Issue by samnabi** [funmusicplace/mirlo#669]
On the "Edit Album" page, whenever I try to add a listed artists it doesn't save the information. (I assume this is supposed to be a structured way to add featured artists such as `Song Name (feat. Other Artist)`

As it stands now, I just added the featured artists into the song name.

**Comment by simonv3** [comment]
@samnabi are you still seeing this?

**Comment by samnabi** [comment]
I am able to add and save an artist name now, but it doesn't show up anywhere in the track listing.
<img width="718" alt="Screen Shot 2024-05-10 at 3 14 04 PM" src="https://github.com/funmusicplace/mirlo/assets/1731536/faff6a8d-db4b-458d-b84e-591aefe9d
<img width="675" alt="Screen Shot 2024-05-10 at 3 13 55 PM" src="https://github.com/funmusicplace/mirlo/assets/1731536/1c232579-92b9-4a3c-a101-9cf6b648e5ac">
1d3">

**Comment by simonv3** [comment]
Ah yeah I think we hadn't implemented that bit yet. Should be quick.

**Comment by simonv3** [comment]
@samnabi did you mark Felix as a co-author on the track? I'm not sure if that's the right word choice there, but that's what determines if someone will get listed publicly on a track listing. 

eg. 
![image](https://github.com/funmusicplace/mirlo/assets/485583/f610d7d1-fbbd-4f7e-aaae-ffb6455a1565)

**Comment by samnabi** [comment]
I did, and it didn't show up in the track title. Maybe it's not showing because the track is not released yet?

On a separate note, I find the language of "co-author" confusing, and not sure what exactly the checkbox is supposed to do. It might be useful to refer to Distrokid's FAQ on different artist roles here: https://support.distrokid.com/hc/en-us/articles/1500006478301-What-Are-Artist-Roles

What I'm looking for is a way to add someone as a featured artist (so their name shows up in the Track Title), but there should also be a way for them to be formatted as a remixer, or as a secondary "main" artist on the track (i.e. listed in the Artist Name, not the Track Title)
