### ISSUE TITLE
Artist page - Edit Artist form, add labels to image uploads

### ISSUE THREAD

**Issue by CPacaud123** [funmusicplace/mirlo#709]
On Edit Artist form, would be nice to identify/label the two image files that can be uploaded (Banner and Avatar).

![image](https://github.com/funmusicplace/mirlo/assets/82707161/bf842a5d-542a-40f7-b57f-832e6edd8926)

As discussed here:
https://discord.com/channels/1070731899317796974/1163870119215255562/1236351356126888046

**Comment by LouisLouiseKay** [comment]
Should be fixed once we push this PR https://github.com/funmusicplace/mirlo/pull/735
