### ISSUE TITLE
Profile - Follow notifications seem incomplete

### ISSUE THREAD

**Issue by CPacaud123** [funmusicplace/mirlo#716]
I have received notifications for users following one of my artists. I have four bound to my profile, and the notifications do not specify which one was followed, and I presume they're supposed to do so.

![image](https://github.com/funmusicplace/mirlo/assets/82707161/b8ebd7ab-6522-4f8c-a17b-56a4b6bd6a85)

**Comment by simonv3** [comment]
Going to close this as a more specific case of #665
