### ISSUE TITLE
Track numbers all say 1

### ISSUE THREAD

**Issue by timglorioso** [funmusicplace/mirlo#728]
I uploaded tracks one-by-one to [this album](https://mirlo.space/care-package/release/i-wanna-swim). The track numbers all say "1" rather than increment as expected.

I looked for a way to edit this but didn't see anything.

**Comment by simonv3** [comment]
Hmm, that should get set here https://github.com/funmusicplace/mirlo/blob/main/client/src/components/ManageArtist/BulkTrackUpload.tsx#L142

I wonder why that happened in this instance (it looks like it's working fine in other recent albums). If you click and drag a track around, does it fix it?

**Comment by timglorioso** [comment]
That did it, thanks.

Just thinking out loud, if I selected the files for upload one-by-one, would it still use BulkTrackUpload?

**Comment by simonv3** [comment]
Possibly, might need to add a little state-check logic that checks whether tracks already exist on the album. It might be worth doing this on the back-end?

**Comment by timglorioso** [comment]
This is what I get for being "nice" to the server :P

I haven't done much poking around on the backend, lemme see...
