### ISSUE TITLE
Images in updates get cut off when sent as base64

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#742]
![blob](https://github.com/funmusicplace/mirlo/assets/485583/a1727e4a-614e-4e2f-85e3-284a4ba5ab36)

I suspect this is happening because some email clients cut off emails after certain length (gmail). 

One solution to this is to upload images to minio for blog posts. Nice added layer of complexity :(

Going to first try this though https://stackoverflow.com/questions/41946783/gmail-blocking-small-embedded-inline-images-in-email-template/68532260#comment129526488_68532260

> Looking further at the Nodemailer doc, it looks like this package is not (or no longer?) useful: we only need to add attachDataUrls: truein the sendMail options.

**Comment by simonv3** [comment]
@peterklingelhofer was this fixed in the last few announcement emails?

**Comment by peterklingelhofer** [comment]
@simonv3 Yep, no more duplicates over here
