### ISSUE TITLE
Amount paid description in email confirmation for album purchase seems wrong

### ISSUE THREAD

**Issue by CPacaud123** [funmusicplace/mirlo#749]
I just got a confirmation email for my first purchase on Mirlo. The amount paid shown is wrong (I paid USD 15.00, it indicates USD 2.00).

**Comment by simonv3** [comment]
That's a pretty serious miscalculation! Could you attach a screen shot of the e-mail if you don't mind?

**Comment by CPacaud123** [comment]
No prob, sorry for the wait. Here you go!
![image](https://github.com/funmusicplace/mirlo/assets/82707161/cd473e20-8605-4794-86f8-ef6132302455)
