### ISSUE TITLE
Issue when buying an album without an account and trying to log in

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#753]
I bought this [1] album on the site using this email address and I
received a download link with an URL including a token.

[1]: https://mirlo.space/lminiero/release/axiom-(ep)

However, clicking on the URL just refreshes the page to [1] again, and
there is no download link available anywhere.

I tried to setup an account to check whether I could get the download
link another way, since the email mentions

> If you want to have access to all your purchases for this e-mail address, simply set a password for it
But signup tells me an account with my email already exists and using
the API call in the reset password email just leads to a JSON error
"this user does not exist".

I'll try tomorrow in case your database needs some time to update but
I'd appreciate if you could check if something's not wrong and let me know.

**Comment by tucker-m** [comment]
Getting the same thing here. JS console shows this:

```
GET https://api.mirlo.space/auth/profile 401 (Unauthorized)

GET https://api.mirlo.space/v1/trackGroups/misaligned-aardvarks?artistId=undefined 404 (Not Found)

API Instance catching error Error: TrackGroup with id undefined not found
```

then it redirects to the regular album page with no token in the URL, and no download links on the page.

**Comment by simonv3** [comment]
> It said there was already an account for my email address (which I don't remember creating, must have been created because I purchased the album), so I reset my Mirlo account password using that email address. Now the album has a download link.

Yeah we auto create an account for anyone who's bought an album. We can change our error message to include a check for if a password was set at all, in which case we should say something like "This account already exists, but you still need to set a password".

**Comment by simonv3** [comment]
Handled this part of this issue: 

> However, clicking on the URL just refreshes the page to [1](https://mirlo.space/lminiero/release/axiom-(ep)) again, and
there is no download link available anywhere.
