### ISSUE TITLE
Login And Email Subscribe Error

### ISSUE THREAD

**Issue by vance** [funmusicplace/mirlo#762]
I think this is a cool idea! I heard about it on the "It could Happen Here" Podcast. 

I used Chrome for iOS to try to register, got an empty red error toast. 

I then tried to follow/subscribe to an artist, also got error toast. 

![image](https://github.com/funmusicplace/mirlo/assets/145471/724486a8-3610-4cd3-a19e-639009513986)

**Comment by simonv3** [comment]
Hey @vance, thanks for the report! Does your email have a "+" in it by any chance?

**Comment by vance** [comment]
I did not add the `+` this time 😄
