### ISSUE TITLE
uploading multiple files by open file dialog selection does not work

### ISSUE THREAD

**Issue by lukaprincic** [funmusicplace/mirlo#777]
Below 'Attach files from you computer to get started uploading tracks' when I click BROWSE and in the the 'Open file' select multiple files, it creates a text 'x files selected...' next to browse button but then nothing happens.

It works ok when drag-droping multiple files via a file manager, but not as described above.

Linux Ubuntu Mate
browser: LibreWolf 118.0.1-1 (- it's basicaly a firefox)

**Comment by simonv3** [comment]
Hmm, could you do a screen cap, and maybe let me know what browser you're using? 

On Firefox on Linux Mint this seems to work 

[video(1).webm](https://github.com/funmusicplace/mirlo/assets/485583/dfcfbc61-4d54-4d7e-b3e9-bd1fad1903a3)

(though the upload is pretty slow)

**Comment by lukaprincic** [comment]
now it works. sorry, i cannot reproduce the problem. I guess you/we can close the issue. Sorry for the noise.

**Comment by simonv3** [comment]
No worries, thanks for reporting it! Keep an eye and see if it happens again.
