### ISSUE TITLE
Is there a particular reason for this issue?

### ISSUE THREAD

**Issue by LWFlouisa** [funmusicplace/mirlo#789]
My audio on there sounds several octaves lower than when I uploaded, giving me completely the wrong impression of my voice and the octaves of which I play piano.

**Comment by Coehill** [comment]
Can you please confirm whether you experience this issue from a different browser/device?

**Comment by simonv3** [comment]
Very strange! Is it just your voice that's affected? Or the entire song? It sounds like librewolf is a wrapper around firefox, so I wonder what kind of changes it's making. 

We don't change audio except for converting it into new formats for streaming & downloading
