### ISSUE TITLE
"Donate" button too big for the top bar on mobile

### ISSUE THREAD

**Issue by Cwpute** [funmusicplace/mirlo#794]
My screen is 720x1520 and the "Donate" button at the top left wf the screen takes way too much space.  ranted the translation make it take more space, but it should be taken into account.
The search bar is too tiny in that situation, and not very usable.

[![Screenshot-20240808-004506.png](https://i.postimg.cc/vmnRMPJ0/Screenshot-20240808-004506.png)](https://postimg.cc/jWR34hdf)

The solution i'd suggest is to have that button take its own separate bar below the top bar, that would disapear with scrolling as does that top bar.

**Comment by Cwpute** [comment]
Another solution would be to have the search field automatically turn into a Magnifying glass icon if it's too small. Then, when the user taps wn it, it expands and take the whole bar as to see what you're typing inside.

**Comment by simonv3** [comment]
is there a good icon for the donate button that we could collapse the button to on small screens? something from https://react-icons.github.io/react-icons/

**Comment by Cwpute** [comment]
The first that came to mind was a hand receiving a heart: ``<FaHandHoldingHeart />`` could do.
