### ISSUE TITLE
Bottom page FAQ link is broken

### ISSUE THREAD

**Issue by Cwpute** [funmusicplace/mirlo#795]
Instead it shows ``<faq>FAQ</faq>``

**Comment by simonv3** [comment]
is this in french? i think the translation has to be updated to that it doesn't have an faq anymore

**Comment by Cwpute** [comment]
yes it's french.
i'm also managing the french translation and i don't recall seeing this string waiting for an updated translation lately ? i may have missed the notif but i'm pretty all french strings have been translated, some are just waiting for approval.

Le 8 août 2024 14:26:01 GMT+02:00, Psi ***@***.***> a écrit :

**Comment by simonv3** [comment]
https://app.transifex.com/mirlo/mirlo/translate/#fr/mirlo/475963907?q=text%3A'about+us'

yeah maybe a notification didn't make it`?

**Comment by Cwpute** [comment]
will give it a look sometimes this weekend

**Comment by Cwpute** [comment]
Looking at the history of thats string, it seems the original translation was made by LLK a good bunch of months ago, but when @simonv3 updated the original string, they also also automatically (?) accepted the old string translation as a correct one for the current version.
This i had already spotted before on string#213 , but didn't think it would have impacted other strings !… i guess i'll have to take a broader look at all previous translations to spot any more of those mistakes.
