### ISSUE TITLE
No valid subscription available

### ISSUE THREAD

**Issue by Cwpute** [funmusicplace/mirlo#799]
Found a situation in which the artist hadn't set any subscription option, so whin i tried to subscribe i had no valid option and wasn't presented any :
[![Screenshot-20240808-013952.png](https://i.postimg.cc/cHLfDXSD/Screenshot-20240808-013952.png)](https://postimg.cc/KKCKj74L)

The button below wouldn't let me click it even if i gave it an email adress to chew on.

A user should be presented with at least one option, even if the artist hasn't set any.
There could be a default text saying "Give us your email and stay updated on this artist's activity, and consider telling your fruends about it" with a button to copy this page's link to the clipboard.

**Comment by simonv3** [comment]
@Cwpute i think this might be the wrong screenshot?

**Comment by Cwpute** [comment]
yes sorry, i changed it to the correct one.

**Comment by simonv3** [comment]
yeah, artist basic follow tier should be automatically set automatically

https://mirlo.space/dream-of-omnimaga/posts/76/  looks like thats from this page. weirdly enough i'm having the follow tier show up ;/

is this happening on desktop too?

**Comment by Cwpute** [comment]
can't say right now. since issue #795 was caused by a translation issue, i wonder if this one could be as well… i'll take a look.

**Comment by Cwpute** [comment]
tried it today on desktop, and the a subscription tier did appear, although with a simgle second of delay after the subscription window was opened.
my android browser is Fulguris, amd i suspect it has something to do with content control options i had set up for it, let me check.

**Comment by Cwpute** [comment]
ok, even with Content Control on, the contribution tier appeared… after a good 8 seconds.
This is probably only due to my own internet connection being unreliable, and that initial "bug" only caused by a suspended connection at the worst moment.

You could probably still show a placeholder tier with no text and a loading icon inside, to show the tier might not be loaded, but still available if you wait long enough. That would prevent other people like me thinking the whole thing isn't working 😂
I'll let you close this issue if you don't think a visual buffer isn't worth implementing.
