### ISSUE TITLE
Little mistake in French translation

### ISSUE THREAD

**Issue by nicoalto** [funmusicplace/mirlo#811]
Hi,

Some very little mistakes in French translation, when buying an album:
- 93% (...) Ce calcul n'**inclut** pas
- **Nous** vous encourageons (capitalize)
- Nous ne sommes pas toujours **capables**

Thanks,
Nicolas

![Capture d’écran 2024-08-17 112157](https://github.com/user-attachments/assets/7254ea1d-bf17-4eb7-818d-5f6d1713bf9a)
Link example: https://mirlo.space/nicolas-hussein/release/compositions-vocales

**Comment by simonv3** [comment]
@Cwpute tagging you on this

**Comment by Cwpute** [comment]
Hi there @nicoalto , good job spotting those. I regonize these mistakes as mine, and i can even spot another one… must have been a sleepy day 😴
If you want, feel free to join the translation team and correct these mistakes by yourself on Transifex: https://app.transifex.com/mirlo/mirlo/
Let me know if you'd rather let me do that.

We're always looking for volunteer translators, especially if you know of other languages that Mirlo still isn't translated to !

**Comment by nicoalto** [comment]
Thanks! I sent a request to join the translation project.

**Comment by simonv3** [comment]
Closing this here as it's better handled in transifex!
