### ISSUE TITLE
I am getting this same error today trying to get a free download link for an album: https://mirlo.space/nicolas-hussein/release/orchestrations

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#813]
I am getting this same error today trying to get a free download link for an album: https://mirlo.space/nicolas-hussein/release/orchestrations

I tried the artist's other albums and I am getting the same error as well.

![image](https://github.com/user-attachments/assets/8c57a449-af50-43c7-b4f8-d07b831d3f6c)

_Originally posted by @CPacaud123 in https://github.com/funmusicplace/mirlo/issues/787#issuecomment-2294827801_

**Comment by simonv3** [comment]
@CPacaud123 hmm, this feels like it's a different issue. 2 or the 3 albums by this artist didn't have product keys associated with them (though the one you link above did) which means that those two hadn't been purchased before. 

I think what's happening to you (and I managed to replicate it) is that you're not logged in and the e-mail field was left blank. The bug here is that you shouldn't be able to press purchase in that instance, but it's a different bug. Would you mind creating a new issue for it just so that we can track it differently? Should be a relatively easy fix.

**Comment by CPacaud123** [comment]
Will do, thanks! Just to be clear though, the Email field at the bottom was filled in when I was getting the error. The top one was left empty.

**Comment by simonv3** [comment]
accidentally made my own ticket and then also asked you to make one 😆

**Comment by CPacaud123** [comment]
Haha I noticed, I was like ¯\_(ツ)_/¯ ! No worries, made me laugh :P
