### ISSUE TITLE
Clarification on "default" licence

### ISSUE THREAD

**Issue by Cwpute** [funmusicplace/mirlo#815]
About the.recently added string in `manageAlbum.whatMeanLicense`, for reference:
> Don't know what this means? Just leave it blank! By default all works are copyrighted

The text here is very vague and unhelpful, and leaves you with more questions than answers.
Does Mirlo select a default licence for tracks that are not explicitely set with one ? or are you talking more broadly, saying art works are copyrighted under a certain licemce the moment they are shared by their author ? or does Mirlo enforce its own handcrafted licence upon works shared on its platform ?

**Comment by Cwpute** [comment]
Interesting, i didn't know that.
I'm also reading about the TRIPS agreement which seems to cover a good lot more countries (https://en.m.wikipedia.org/wiki/TRIPS_Agreement).

We can assume people don't know about either TRIPS or Berne and probably don't care. But i appreciate the effort to inform others, and it should be kept in.

The original text is essentially comprised of 3 informations:
1. your text is automatically copyrighted in most countries
2. you can add a custom licence if you want
3. it's ok to not care about it all

So i'd rework the UI/UX (not too familiar about these fields but here i go anyway):
In place of the current licence options, some text and a button. The would read:
> Depending on your country, your work is most likely copyrighted under the Berne Convention and/or the TRIPS agreement (more about it here).
Immediately below, a button with a plus sign "Add a custom licence", which would bring up the current panel of options to attach a different licence to your work.

**Comment by simonv3** [comment]
That language sounds good--I think in the interest of space, maybe it makes the most sense as a pop up or tooltip?

**Comment by Cwpute** [comment]
if by a tooltip you mean some kind of popup behind a sign like ℹ️, yeah i'm all for it.
