### ISSUE TITLE
Currency tag not working before payout

### ISSUE THREAD

**Issue by Cwpute** [funmusicplace/mirlo#816]
It seems the {{currency}} tag in the string `nameYourPrice": "Name your price in {{ currency }}:"` doesn't work.
As you can see from the screenshot in #811, the currency doesn't align with that which is used in the string below the user-set price "93% of this amount (amount+currency) will go to…"

**Comment by Cwpute** [comment]
Can also be seen here: https://mirlo.space/samnabi/release/sam-nabi-and-friends
![](url)

**Comment by simonv3** [comment]
Duplicate of #810
