### ISSUE TITLE
bio text dissapears when new artist is saved

### ISSUE THREAD

**Issue by lukaprincic** [funmusicplace/mirlo#834]
I created a new artist. Added name, avatar image, then wrote the bio, then uploaded the background image, and then clicked save. The bio was empty. Other stuff got saved.

This is not the first time some text was simply lost like this. Is there something in the background of these dynamic pages that is causing this? Sorry for the kinda vague questioning, I never got into the nodejs or eliksir or these 'new' front end web languages.

I'm on Linux, with LibreWolf (Firefox fork)

**Comment by samnabi** [comment]
This might be related to another issue I'm seeing. Text fields seem to be saved when the `onBlur` event is triggered, But if you click the Save button without losing focus on that field, it won't save the content. 

Maybe it's better to save content `onInput`, i.e. as you type, and try to redesign these forms without a separate Save button.

https://github.com/user-attachments/assets/3d80554c-e7d1-4d95-b3d7-4d5e21ea6a72

**Comment by simonv3** [comment]
I wrote up a thing about how I think those are separate issues but i guess I didn't press send-- @samnabi do you mind making a new ticket for that? that looks like it's on the album page (as opposed to the artist page) and I couldn't replicate it right away
