### ISSUE TITLE
text edit fields do not update properly after update

### ISSUE THREAD

**Issue by lukaprincic** [funmusicplace/mirlo#837]
When editing description of the album, updating and saving updates the rendered page, but when returning to edit of the page immediately, it shows the old, pre-edited text.

https://github.com/user-attachments/assets/1d0fdbe9-5d0d-48da-bc0e-494f031da1f4

(browser: LibreWolf 122)

**Comment by simonv3** [comment]
Ah this looks like a caching issue. If you reload the page is the new data in the form?

**Comment by simonv3** [comment]
I _think_ I merged some changes that will hopefully have fixed this. LMK if you're still seeing this @lukaprincic

**Comment by lukaprincic** [comment]
> I _think_ I merged some changes that will hopefully have fixed this. LMK if you're still seeing this @lukaprincic

i can confirm that this is fixed. thank you!
