### ISSUE TITLE
Link merch item to digital release

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#861]
I'd say this one is pretty critical : 

When someone purchases a merch item, the creator should be able to link said item to a digital release, in which case the purchase of said item will include the download of said release and add it to their collection.

Simon adding a todo: 

* [x] Let an artist link an album to a merch item.
* [x] Display merch on the album page as an option to buy
* [x] Display the related album on the merch page 
* [x] When purchasing the merch, automatically add the album to the user's collection

**Comment by simonv3** [comment]
Yeah agreed. There's a column for it in the merch table, but there's a lot of logic and UI that needs to be built for it to happen. Feels do-able in the near future though.

**Comment by LouisLouiseKay** [comment]
I think ideally in the end UI/UX, it's just a dropdown "link this item to one of your digital releases". Bandcamp has a "what album is it?" dropdown for that, and it sits at the top of the merch form next to title. We could put it underneath it.

**Comment by simonv3** [comment]
oh yeah, that part is easy. It's the "what happens when you buy the merch" that's more complicated

**Comment by simonv3** [comment]
@LouisLouiseKay actually does it make sense to just redirect to the album page for a merch item publicly? So on the Merch page, if an artist clicks on a vinyl, should it take them to the album page or to the page for the merch itself?
