### ISSUE TITLE
On album page, text fields don't always save when clicking save button

### ISSUE THREAD

**Issue by samnabi** [funmusicplace/mirlo#884]
Text fields seem to be saved when the `onBlur` event is triggered, But if you click the Save button without losing focus on that field, it won't save the content.

Maybe it's better to save content `onInput`, i.e. as you type, and try to redesign these forms without a separate Save button.

https://github.com/user-attachments/assets/912c3cdf-2785-43d5-9f66-08abf4dee283

**Comment by simonv3** [comment]
@samnabi taking a look at this now, I can't quite reproduce it. what browser are you using?

**Comment by samnabi** [comment]
Looks good!
