### ISSUE TITLE
Tracklisting on merch page takes too much space

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#895]
As shown in this ticket https://github.com/funmusicplace/mirlo/issues/894 tracklisting takes way too much space.

It would not be an issue at all in my opinion if the tracklisting on the merch item page was written much smaller, as this page is for people who are already quite convinced by the music, it's not a "discovery" page, the merch should be front and center and the tracklist a reminder of what's in that release.

**Comment by simonv3** [comment]
@LouisLouiseKay should the tracklist be playable still?

**Comment by LouisLouiseKay** [comment]
Could be nice, but it's not necessary (as in, we can do that later if it causes issues)
