### ISSUE TITLE
POST http://localhost:3000/auth/login 401 (Unauthorized)

### ISSUE THREAD

**Issue by tsalsa919** [funmusicplace/mirlo#914]
I have followed Contribution guide:

https://github.com/funmusicplace/mirlo?tab=readme-ov-file#contributing

When loading the client at http://localhost:8080  the following is showing up in the console. 

`POST http://localhost:3000/auth/login 401 (Unauthorized)`

Is there something ought to be set on the api end to allow COR or client access?

**Comment by simonv3** [comment]
Just to confirm:

did you run the seed script:

```
docker exec -it blackbird-api yarn prisma:seed
```

Then check if you've copied the env files into the right locations (both in the server and _in_ the client folder?) 

If yes to both of those then my next question would be: are you able to connect to the database via a client like dbeaver and see what's in the `Client` table?

And are you able to see the server logs? If you're using the `docker compose watch` command you'll need to run logs in a separate window:

```
docker compose logs -f
```

**Comment by tsalsa919** [comment]
Hey, 

So I can psql into the docker container and got the `public."Client" table`

`nomads=# select * from public."Client" ;
 id | applicationName |    applicationUrl     |   allowedCorsOrigins    |        updatedAt        |        createdAt        | deletedAt 
----+-----------------+-----------------------+-------------------------+-------------------------+-------------------------+-----------
  1 | frontend        | http://localhost:8080 | {http://localhost:8080} | 2024-11-24 00:06:26.105 | 2024-11-24 00:06:26.105 |
`

Also this the client/.env
```

PORT=8080 
VITE_API_DOMAIN=http://localhost:3000 

# Note the below must match the PORT above and also the first
# value stored in the Client table under the "frontend" row
# in the cors column
VITE_CLIENT_DOMAIN=http://localhost:8080tree@system-seventy-six:~/git/mirlo$
```

**Comment by simonv3** [comment]
Okay so it looks like the client is created and your env file is setup. 

When you load the client and have the server running, and you try to log in, what do the logs of the server say?

```

**Comment by tsalsa919** [comment]
We can close this issue. The issue might be related to my specific docker setup and how the bridge network was interacting.

**Comment by simonv3** [comment]
Curious! Let's see if it resurfaces. Thanks for trying @tsalsa919
