### ISSUE TITLE
Issues with mobile viewing not displaying full page

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#96]
The mobile view doesn't display the full page upon landing, you need to "zoom out" in order to be able to read full text.

![Screenshot_2023-09-29-10-02-07-340_com android chrome](https://github.com/funmusicplace/mirlo/assets/77789607/62820c02-5da5-4293-ba28-861956daa0c1)

**Comment by simonv3** [comment]
Should be fixed @LouisLouiseKay
