### ISSUE TITLE
Dark theme readibility issues

### ISSUE THREAD

**Issue by LouisLouiseKay** [funmusicplace/mirlo#97]
The footer and the menu are both in parts unreadble in dark mode
![Screenshot_2023-09-29-10-02-25-598_com android chrome](https://github.com/funmusicplace/mirlo/assets/77789607/20c9f3db-1b8c-43bc-8514-460be167ab72)
![Screenshot_2023-09-29-10-09-30-598_com android chrome](https://github.com/funmusicplace/mirlo/assets/77789607/35fc8489-e6d8-4b8f-a629-720d27ca3f87)

**Comment by simonv3** [comment]
Should also be fixed @LouisLouiseKay , let me know if you find weirdness in other spots
